apiVersion: v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 9471
          envFrom:
            - configMapRef:
                name: postgres-configmap
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name:
            configMap:
              name: postgres-configmap
