apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: default
data:
  POSTGRES_DB: mydb
  POSTGRES_PORT: 9471
  POSTGRES_PASSWORD: adminpwd
  POSTGRES_HOST: 10.0.2.15
  POSTGRES_USER: admin